<?php
    $lang = array(
        //nav_bar
        "address" => "BD BIR ANZARANE HAY HASSANI Imm ERAC",
        "opntim" => "Horaires d'ouverture: lundi-samedi: 8h30 à 18h30",
        "apdn" => "À Propos De Nous",
        "cnb" => "Contactez Nous",
        "lang" => "langue",
        "appn" => "Appelez-nous",
        "enum" => "Envoyez nous un Mail",
        "tittle" => "Morgan Assurance",
        "vodevbu" => "Votre Devis",
        "nosserbut" => "Nos services",
        "listtdam" => "Transfert D'argent au Maroc",
        "listtdi" => "Transfert d'argent international",
        "listpdf" => "Paiement de factures",
        "listpdva" => "Paiement de vignette automobile",
        "listpdet" => "Paiement Des Impôts et taxes",
        "listaebdvc" => "Achat de billets de voyage CTM",
        "listpeed" => "Paiement en espéces d'achat",
        "nbcbutt" => "Contact",
        "nbllbutt" => "Localiser L'Agence",
        //end_of_nav_bar

        //fotter
        "fottitpar" => "Avec Morgan Assurance, Bénéficier de plusieurs types d'assurances",
        "fotcbut" => "Contacts",
        "fotadris" => "BD BIR ANZARANE HAY HASSANI Imm ERAC, YOUSSOFIA",
        "fotcopr" => "Copyright © 2020",
        "fotcoptitle" => "Morgan Assurance",
        "fotagr" => "All rights reserved",
        //end_of_fotter

        //home_page
        "hometitle" => "Avec Morgan Assurance, Bénéficiez de plusieurs types d'assurances",
        "homepi" => "Plus d'infos",
        "hometvda" => "Votre Devis Assurance en quelques Minutes",
        "homecvd" => "Calculez Votre Tarif",
        "homepre" => "Previous",
        "homenex" => "Next",
        "hometpart" => "Partenaires",
        "homenstit" => "Nos Services",
        "hometdam" => "TRANSFERT D’ARGENT AU MAROC",
        "hometdamp" => "Envoyez ou recevez votre argent partout au Maroc grâce à un large réseau fiable de plus de 2000 agences.",
        "homeespbut" => "EN SAVOIR +",
        "hometdi" => "TRANSFERT D’ARGENT INTERNATIONAL",
        "hometdip" => "Recevez votre argent envoyé depuis l’étranger dans une agence de transfert d’argent Cash.",
        "homepdf" => "PAIEMENT DE FACTURES",
        "homepdfp" => "Vous pouvez payer vos factures d’eau et d’électricité ou votre abonnement INWI rapidement dans ...",
        "homepdva" => "PAIEMENT DE VIGNETTE AUTOMOBILE",
        "homepdvap" => "vous pouvez payer les frais de votre vignette automobile en toute rapidité et sans prise de rendez-vous.",
        "homepdet" => "PAIEMENT D’IMPOTS ET TAXES",
        "homepdetp" => "Le paiement de l’IS, l’IR, et la TVA ainsi que les autres taxes telles que la taxe d’habitation, de services communaux se fait dans toutes les agences de...",
        "homeadbdvc" => "ACHAT DE BILLETS DE VOYAGE CTM",
        "homeadbdvcp" => "Achetez vos billets de voyage nationaux dans plus de 2000 agences.",
        "homepeedesds" => "PAIEMENT EN ESPÈCES D'ACHATS EFFECTUÉS SUR DES SITES DE COMMERCE",
        "homepeedesdsp" => "Effectuez votre achat en ligne et payez dans l’agence de transfert d’argent la plus proche de chez vous.",
        "hometeptitle" => "Transfert et Paiement",
        "hometeppat" => "Transfert D'argent au Maroc et international",
        "hometeppaad" => "Paiement de vignette automobile",
        "hometeppape" => "Paiement en espéces d'achat",
        "hometeppapd" => "Paiement D'impots et taxes",
        "homepdibut" => "Plus d'infos",
        "hometepcn" => "Contactez Nous",
        "hometepcnp" => "Contactez-nous en appuyant sur le bouton ci-dessous et en remplissant le formulaire",
        //end_of_home_page

        //contact_page
        "contacttipag" => "Contact",
        "contactname" => "Name",
        "contactemaadr" => "Email Address",
        "contactsub" => "Subject",
        "contactmess" => "Message",
        "contactbbuttsub" => "Submit",
        //end_of_contact_page

        //devis_page
        "devbititt" => "Votre Devis Morgan auto personnalisé",
        "devsmatitt" => "Votre devis Morgan auto personnalisée vous souhaitez avoir plus de garanties? renseignez ce formulaire et obtenez la formule avec un prix adapté à votre besoin",
        "devmidtitt" => "Remplir le formulaire",
        "devtyca" => "-- Type Carburant --",
        "devdi" => "Diesel",
        "devess" => "Essence",
        "devcalcbut" => "Calculez",
        "devtrttan" => "Trif TTC / 1 ans",
        "devdh" => "---- Dhs",
        "devtrttmo" => "Trif TTC / 6 mois",
        "devresciv" => "Responsabilité civile",
        "devcugo" => "C’est une garantie obligatoire. Elle couvre l’indemnisation des dommages corporels et matériels causés à des tiers par le véhicule assuré.",
        "devpadllp" => "Dans les limites prévues par le contrat d’assurance Morgan.",
        "devcapiass" => "Capital assuré:",
        "devddhh" => "1000000 Dhs",
        "devddeerr" => "Défense et recours",
        "devggldd" => "Garantie la défense des intérêts des personnes assurées dès lors qu’elles sont poursuivies à la suite d’un événement en relation avec le véhicule assuré. Elle permet aussi l’obtention de la réparation pécuniaire des dommages subis par le véhicule ainsi que les dommages non indemnisés par une autre assurance, subis par le véhicule assuré.",
        "devddllp" => "Dans les limites prévues par le contrat d’assurance Morgan.",
        "devmoney" => "10000 Dhs",
        "devevca" => "Évènement catastrophiques",
        "devggrpln" => "Garantie régie par la loi n° 110-14 instituant le régime de couverture des événements catastrophiques et obligatoire à effet de janvier 2020.",
        "devconcon" => "Conséquences d’évènements catastrophiques adossées à la garantie RC automobile:corporel 0 Dhs",
        "devdevdev" => "Conséquences d’évènements catastrophiques adossées à la garantie RC automobile:materiel Valeur vénale Max. 200 000 DH",
        "devcatcat" => "Conséquences d’évènements catastrophiques adossées aux garanties dommages au véhicule Valeur vénale Max. 200 000 DH",
        "devpropas" => "Protection Passagers",
        "devveci" => "Protège toutes les personnes transportées gracieusement à bord de son véhicule, et ce indépendamment de sa responsabilité dans la survenance du sinistre.",
        "devsécé" => "Décès",
        "devétic" => "Incapacité",
        "devtion" => "Frais hospitalisation",
        "devcaux" => "Frais médicaux",
        "devdhss" => "Dhs",
        
        //eng_of_devis_page

        //services_page
        "servtone" => "TRANSFERT D’ARGENT AU MAROC",
        "servpone" => "Où que vous soyez au Maroc , vous pouvez recevoir de l’argent de l’étranger, envoyé via Western Union , MoneyGram , Moneytrans , Ria,... dans l’une de nos agences de transfert d’argent. Vous allez recevoir votre argent instantanément dans l’une des nos 2000 agences.",
        "servppone" => "Cash Plus vous assure un transfert d’argent au Maroc sécurisé, rapide et fléxible. Vous cherchez une agence de transfert d’argent à Casablanca, à Marrakech, à Rabat ou à n’importe quelle ville au Maroc",
        "servttwo" => "Transfert d'argent international",
        "servptwo" => "Où que vous soyez au Maroc , vous pouvez recevoir de l’argent de l’étranger, envoyé via Western Union , MoneyGram , Moneytrans , Ria,... dans l’une de nos agences de transfert d’argent. Vous allez recevoir votre argent instantanément dans l’une des nos 2000 agences.",
        "servpptwo" => "Cash Plus vous assure un transfert d’argent au Maroc sécurisé, rapide et fléxible. Vous cherchez une agence de transfert d’argent à Casablanca, à Marrakech, à Rabat ou à n’importe quelle ville au Maroc",
        "servttree" => "PAIEMENT DE FACTURES",
        "servptree" => "En plus des autres services que propose Cash Plus tels que l’envoi d’argent en ligne ou en agence, Cash Plus vous permet également de payer vos factures d’eau et d’électricité en toute rapidité dans l’agence la plus proche. Grâce à son partenariat avec Fawatir et les régies d’eau et d’électricité de différentes villes du royaume dont LYDEC , RADEEMA , RAMSA , RADEEF , RAK , REDAL , AMENDIS,.. .vous pouvez payer vos factures d’eau et d’électricité dans l’agence Cash Plus la plus proche.",
        "servpptree" => "Vous pouvez également payer chez Cash Plus votre facture d’abonnement INWI, Orange et Maroc telecom.",
        "servtfor" => "PAIEMENT DE VIGNETTE AUTOMOBILE",
        "servpfor" => "VOUS N’AVEZ TOUJOURS PAS PAYÉ LA VIGNETTE 2020 ?",
        "serppfor" => "Vous pouvez en quelques minutes seulement, sans prise de rendez-vous, et à seulement 23 Dhs TTC vous acquitter des frais de votre vignette automobile en toute simplicité et rapidité chez l’agence Cash Plus la plus proche de vous.",
        "servpppfor" => "Nos agences sont ouvertes de 8h00 à 20h00 du Lundi au Samedi.",
        "servppppfor" => "N'hésitez pas à contacter l'agence Cashplus la plus proche pour plus d'information.",
        "servtfive" => "PAIEMENT D’IMPOTS ET TAXES",
        "servpfive" => "Particuliers :",
        "servppfive" => "Dans l’une des 2000 agences Cash Plus de transfert d’argent, là où que vous soyez, vous pouvez payer votre taxe d’habitation, de services communaux , votre impôt sur le revenu (IR) mais aussi les amendes pour infractions routières",
        "servpppfive" => "Entreprises :",
        "servppppfive" => "Fini les queues interminables pour payer vos impôts! Désormais, le paiement de l’IS, l’IR, et la TVA est disponible dans tout le réseau Cash Plus.",
        "servpppppfive" => "Grâce à ses horaires flexibles (8h30 - 20h30), des agences de permanence ouvertes le dimanche, et sa présence sur tout le territoire national avec plus de 2000 agences, vous avez la possibilité de payer l’IS , l’IR et la TVA en toute rapidité et partout au Maroc. Il suffit de vous adresser à l’agence Cash Plus la plus proche.",
        "servtsix" => "ACHAT DE BILLETS DE VOYAGE CTM",
        "servpsix" => "Payez vos billets de voyages nationaux CTM chez Cash Plus en vous adressant à l’agence la plus proche et voyagez en toute sécurité , rapidité et confort .",
        "servtsiven" => "PAIEMENT EN ESPÈCES D'ACHATS EFFECTUÉS SUR DES SITES DE COMMERCE",
        "servpsiven" => "Vous voulez faire des achats en ligne sur des sites e-commerce, mais vous préférez payer en cash ?",
        "servppsiven" => "C’est désormais possible avec Cash Plus !",
        "servpppsiven" => "Effectuez votre achat en ligne sur les sites e-commerce partenaires tels que Yves Rocher, Being Sport, VFS Global, Tik Tok, … et payez dans l’agence de transfert d’argent Cash Plus la plus proche de chez vous.",
        "servppppsiven" => "Praticité , rapidité et confiance , c’est ce que l’agence de transfert d’argent Cash Plus vous offre",
        //enf_of_services_page

        //about_page
        "aboutt" => "À Propos De Nous",
        "aboutp" => "un établissement de paiement agréé Bank Al-Maghrib qui offre à ses clients une panoplie complète de services financiers et para-financiers.",
        "aboutpp" => "Expert du transfert d’argent depuis plus de 12 ans, permet aujourd’hui à ses clients, en plus d’envoyer et de recevoir leur argent partout au Maroc, de recevoir leurs mandats depuis l’étranger et de payer leurs factures et leurs impôts.",
        "aboutppp" => "Mettant le client au centre de sa stratégie d’entreprise, a développé un large réseau de plus de 2000 agences de transfert d’argent avec des agents formés pour assurer à ses clients un service performant et fiable.",
        "aboutpppp" => "noue des partenariats avec les plus importants acteurs du transfert international notamment avec Western Union, MoneyGram, Moneytrans, Ria, NeoSurf…",
        //enf_of_about_page
    );
?>